import React,{useState,useRef,useEffect,useCallback,Component} from 'react';
import{createRoot}from'react-dom/client';
import{ArrowUpRight,ArrowRight,Camera,Pause,Play,Settings2,Volume2,VolumeX,Maximize,Minimize,X,Compass,MapPin,Sun,ChevronRight,RotateCcw,Download,Trash2,Plane,UserRound,Gamepad2,Image as ImageIcon,Check,Wind,MoveUp,MoveDown,Navigation,Eye,Info,LoaderCircle,House,RefreshCw}from'lucide-react';
import World from './World';
import catalog from '../backend/data/hong-kong.json';
import{createFlight,stepFlight,setMode,setPaused,setCamera,discoverLandmark}from'../backend/src/flight.mjs';
import{readSave,writeSave,photoStore}from'./storage';
import{CabinAudio}from'./audio';
import './style.css';
const scene=catalog.scene,fmt=n=>`${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;
const phases={takeoff:'垂直起飞',transition:'驶向海港',cruise:'海港巡航',approach:'接近西九龙',landing:'平稳降落',arrived:'抵达西九龙'};
const cameraNames={window:'舷窗',forward:'前舱',chase:'外部'};
const IconButton=({icon:Icon,label,...props})=><button className="icon-button" aria-label={label} title={label} {...props}><Icon size={19}/></button>;
class ErrorBoundary extends Component{state={error:null};static getDerivedStateFromError(error){return{error};}render(){return this.state.error?<div className="fatal"><Compass size={42}/><h1>暂时无法打开三维场景</h1><p>请使用支持 WebGL 2 的现代浏览器，并开启硬件加速。</p><button onClick={()=>location.reload()}>重新加载</button></div>:this.props.children;}}
function App(){
 const initial=useRef(createFlight(scene)),flightRef=useRef(initial.current),stageRef=useRef('loading'),keys=useRef({}),apiRef=useRef(null),audio=useRef(null),saveRef=useRef(null);
 const[flight,setFlight]=useState(initial.current),[stage,setStageState]=useState('loading'),[ready,setReady]=useState(false),[loadError,setLoadError]=useState(''),[labels,setLabels]=useState([]),[selectedMode,setSelectedMode]=useState('passenger'),[modal,setModal]=useState(null),[toast,setToast]=useState(''),[saved,setSaved]=useState(null),[photos,setPhotos]=useState([]),[flash,setFlash]=useState(false),[landmark,setLandmark]=useState(null),[storageOk,setStorageOk]=useState(true),[fullscreen,setFullscreen]=useState(false);
 const[settings,setSettings]=useState({audio:false,labels:true,route:true,quality:'high',reducedMotion:matchMedia('(prefers-reduced-motion: reduce)').matches});const settingsRef=useRef(settings);settingsRef.current=settings;
 const notify=useCallback(text=>{setToast(text);},[]);useEffect(()=>{if(!toast)return;const id=setTimeout(()=>setToast(''),4200);return()=>clearTimeout(id);},[toast]);
 const setStage=s=>{stageRef.current=s;setStageState(s);};
 const update=s=>{flightRef.current=s;setFlight(s);};
 const persist=()=>{const ok=writeSave(flightRef.current);setStorageOk(ok);if(ok)saveRef.current=flightRef.current;};
 const pause=reason=>{document.activeElement?.blur();keys.current={};update(setPaused(flightRef.current,reason));persist();};
 const openModal=m=>{if(stageRef.current==='flight')pause('user');setModal(m);};
 const changeMode=mode=>{document.activeElement?.blur();if(stageRef.current==='boarding'){setSelectedMode(mode);return;}update(setMode(scene,flightRef.current,mode));persist();};
 const changeCamera=c=>{document.activeElement?.blur();update(setCamera(flightRef.current,c));apiRef.current?.resetView();persist();};
 const start=(restore=false)=>{document.activeElement?.blur();const state=restore&&saved?saved.state:createFlight(scene,selectedMode);update({...state,camera:restore?state.camera:selectedMode==='pilot'?'chase':'window',pauseReason:restore?'user':null});setStage('flight');setModal(null);persist();};
 const goHome=()=>{persist();const save=readSave(scene);setSaved(save.checkpoint);update(createFlight(scene));setStage('boarding');setModal(null);apiRef.current?.resetView();};
 useEffect(()=>{audio.current=new CabinAudio();const stored=readSave(scene);setSaved(stored.checkpoint);if(stored.error)notify(stored.error);photoStore('getAll').then(p=>setPhotos(p.sort((a,b)=>b.id-a.id))).catch(()=>{});let last=performance.now(),lastUi=0,lastSave=0,frame;
   const animate=now=>{const dt=Math.min(.1,(now-last)/1000);last=now;if(stageRef.current==='flight'){flightRef.current=stepFlight(scene,flightRef.current,keys.current,dt);audio.current.update(flightRef.current.pauseReason===null&&flightRef.current.status!=='arrived');if(now-lastUi>90){setFlight({...flightRef.current});lastUi=now;}if(now-lastSave>5000){setStorageOk(writeSave(flightRef.current));lastSave=now;}}else audio.current.update(false);frame=requestAnimationFrame(animate);};frame=requestAnimationFrame(animate);
   const pressed=new Set();function setKeys(){keys.current={throttle:Number(pressed.has('KeyW'))-Number(pressed.has('KeyS')),turn:Number(pressed.has('KeyD'))-Number(pressed.has('KeyA')),climb:Number(pressed.has('KeyQ'))-Number(pressed.has('KeyE')),hover:pressed.has('Space')};}
   const down=e=>{if(stageRef.current!=='flight'||/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName)||document.querySelector('.modal-backdrop'))return;if(['KeyW','KeyS','KeyA','KeyD','KeyQ','KeyE','Space'].includes(e.code)){e.preventDefault();pressed.add(e.code);setKeys();}if(e.code==='Escape'){setFlight(flightRef.current=setPaused(flightRef.current,flightRef.current.pauseReason?null:'user'));}};
   const up=e=>{pressed.delete(e.code);setKeys();};const lost=()=>{pressed.clear();keys.current={};if(stageRef.current==='flight'&&document.hidden){flightRef.current=setPaused(flightRef.current,'focus');setFlight({...flightRef.current});writeSave(flightRef.current);}};
   const before=()=>{if(stageRef.current==='flight')writeSave(flightRef.current);};const fs=()=>setFullscreen(Boolean(document.fullscreenElement));window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',lost);document.addEventListener('visibilitychange',lost);document.addEventListener('fullscreenchange',fs);window.addEventListener('pagehide',before);
   return()=>{cancelAnimationFrame(frame);audio.current.dispose();window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',lost);document.removeEventListener('visibilitychange',lost);document.removeEventListener('fullscreenchange',fs);window.removeEventListener('pagehide',before);};
 },[]);
 const onReady=useCallback(()=>{setReady(true);setStage('boarding');},[]);
 useEffect(()=>{audio.current?.setEnabled(settings.audio).catch(()=>notify('此浏览器暂不支持声音播放'));},[settings.audio]);
 async function takePhoto(){try{const data=apiRef.current?.capture();if(!data)throw Error();const record={id:Date.now(),image:data,time:fmt(flightRef.current.elapsedSeconds),camera:cameraNames[flightRef.current.camera]};await photoStore('put',record);const all=[record,...photos];if(all.length>12)await photoStore('delete',all.at(-1).id);setPhotos(all.slice(0,12));setFlash(true);setTimeout(()=>setFlash(false),160);notify('照片已保存到本机相册');}catch{notify('照片未能保存，请检查浏览器存储空间后重试');}}
 function downloadPhoto(p){const a=document.createElement('a');a.href=p.image;a.download=`Nextgen-eVTOL-${p.id}.png`;a.click();}
 function visit(lm){setLandmark(lm);update(discoverLandmark(scene,flightRef.current,lm.id,{visible:labels.some(l=>l.id===lm.id),opened:true}));persist();}
 const toggleScreen=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{notify('当前浏览器不支持全屏');}};
 const touchControl=(field,value)=>({onPointerDown:e=>{e.currentTarget.setPointerCapture(e.pointerId);keys.current={...keys.current,[field]:value};},onPointerUp:()=>{keys.current={...keys.current,[field]:field==='hover'?false:0};},onPointerCancel:()=>{keys.current={};}});
 const inFlight=stage==='flight',arrived=inFlight&&flight.status==='arrived',paused=inFlight&&flight.pauseReason!==null&&!arrived;
 return <main className={`app stage-${stage} camera-${flight.camera} ${inFlight&&flight.camera==='window'?'with-cabin':''}`}>
  <World scene={scene} flightRef={flightRef} stageRef={stageRef} settingsRef={settingsRef} onReady={onReady} onError={setLoadError} onLabels={setLabels} apiRef={apiRef}/>
  <div className="atmosphere"/>
  {inFlight&&flight.camera==='window'&&<div className="cabin-frame" aria-hidden="true"><div className="window-rim"/><div className="seat-edge"/><div className="armrest"/></div>}
  {inFlight&&flight.camera==='forward'&&<div className="forward-frame" aria-hidden="true"><span/><span/><div/></div>}
  <header className="topbar"><button className="brand" onClick={()=>inFlight?openModal('menu'):null} aria-label="Nextgen eVTOL 航程菜单"><span className="brand-mark"><i/><i/><i/></span><span>Nextgen <b>eVTOL</b><small>HONG KONG · 2035</small></span></button>
   {inFlight&&<div className="mode-switch glass" aria-label="飞行模式"><button aria-pressed={flight.mode==='passenger'} className={flight.mode==='passenger'?'active':''} onClick={()=>changeMode('passenger')}><UserRound size={16}/>乘客</button><button aria-pressed={flight.mode==='pilot'} className={flight.mode==='pilot'?'active':''} onClick={()=>changeMode('pilot')}><Gamepad2 size={16}/>轻驾驶</button></div>}
   <div className="header-actions"><span className="weather"><Sun size={18}/>香港 · 晴日场景</span>{inFlight&&<button className="pause-button glass" onClick={()=>pause(flight.pauseReason?null:'user')} aria-label={paused?'继续飞行':'暂停飞行'}>{paused?<Play size={18}/>:<Pause size={18}/>}<span>{paused?'继续':'暂停'}</span></button>}<IconButton icon={Settings2} label="设置" onClick={()=>openModal('settings')}/></div>
  </header>
  {stage==='loading'&&<div className="loading-panel glass"><span className="eyebrow">YOUR NEXT PERSPECTIVE</span><h1>香港，即将起飞。</h1><p>{loadError||'正在铺展海港、山形与城市建筑…'}</p>{loadError?<button className="primary" onClick={()=>location.reload()}><RefreshCw size={18}/>重新加载</button>:<><div className="loading-line"/><span className="loading-caption"><LoaderCircle size={14} className="spin"/>准备三维世界</span></>}</div>}
  {stage==='boarding'&&<><section className="boarding-panel glass"><div className="panel-topline"><span className="eyebrow">FIRST FLIGHT / HONG KONG</span><span className="small-tag">观景航程</span></div><h1>维港初航<span>换个高度，<br/>重新认识香港。</span></h1><div className="route-name"><div><span>出发</span><strong>中环海滨</strong><small>CENTRAL</small></div><ArrowRight size={21}/><div><span>抵达</span><strong>西九龙海滨</strong><small>WEST KOWLOON</small></div></div><RouteSketch/><div className="trip-meta"><span><Wind size={15}/>约 5 分 30 秒</span><span><Sun size={15}/>日间观景</span><span>NG-01 · 4 座</span></div><div className="boarding-mode" aria-label="选择出发模式"><button className={selectedMode==='passenger'?'active':''} aria-pressed={selectedMode==='passenger'} onClick={()=>setSelectedMode('passenger')}><UserRound size={19}/><span>乘客观景<small>坐下来，享受风景</small></span>{selectedMode==='passenger'&&<Check size={15}/>}</button><button className={selectedMode==='pilot'?'active':''} aria-pressed={selectedMode==='pilot'} onClick={()=>setSelectedMode('pilot')}><Gamepad2 size={19}/><span>轻驾驶<small>亲手探索维港</small></span>{selectedMode==='pilot'&&<Check size={15}/>}</button></div><button className="primary board-button" disabled={!ready} onClick={()=>start(false)}>开始登机<ArrowUpRight size={24}/></button>{saved&&<button className="resume-link" onClick={()=>start(true)}><RotateCcw size={13}/>继续上次航程 · {fmt(saved.state.routeSeconds)}</button>}<p className="boarding-footnote">飞行途中可以随时切换模式</p></section><div className="location-caption"><span className="location-dot"/><div><strong>中环海滨</strong><span>未来概念起降场 · NG CENTRAL</span></div></div><div className="horizon-label"><span>22°17′ N &nbsp; 114°09′ E</span><div/>VICTORIA HARBOUR</div></>}
  {inFlight&&<>
   <div className="flight-phase"><span className="live-dot"/>{flight.control==='rejoining'?'正在接回航线':flight.control==='holding'?'悬停等候':phases[flight.phase]}<span>NG-01</span></div>
   {!paused&&!modal&&!arrived&&labels.map(l=><button key={l.id} className={`landmark-tag ${flight.visitedLandmarks.includes(l.id)?'discovered':''}`} style={{left:l.x,top:l.y}} onClick={()=>visit(l)}><span className="pin-dot"/>{l.name}{flight.visitedLandmarks.includes(l.id)?<Check size={12}/>:<ChevronRight size={13}/>}</button>)}
   {flight.mode==='pilot'&&!arrived&&<><div className="heading-strip"><span>W</span><i/><b>{String(Math.round((flight.heading*180/Math.PI+360)%360)).padStart(3,'0')}°</b><i/><span>E</span></div><div className="flight-meter speed"><small>速度</small><strong>{Math.round(Math.hypot(flight.velocity.x,flight.velocity.y)*3.6)}<span>km/h</span></strong></div><div className="flight-meter altitude"><small>场景高度</small><strong>{Math.round(flight.position.z)}<span>m</span></strong></div><div className="pilot-help glass"><span><kbd>W</kbd><kbd>S</kbd>前进 / 减速</span><span><kbd>A</kbd><kbd>D</kbd>左转 / 右转</span><span><kbd>Q</kbd><kbd>E</kbd>上升 / 下降</span><span><kbd className="space-key">SPACE</kbd>减速悬停</span></div><button className="handover primary" onClick={()=>changeMode('passenger')}><UserRound size={18}/>交还自动驾驶<ArrowRight size={18}/></button><div className="touch-controls"><button aria-label="左转" {...touchControl('turn',-1)}>←</button><button aria-label="前进" {...touchControl('throttle',1)}>↑</button><button aria-label="右转" {...touchControl('turn',1)}>→</button><button aria-label="上升" {...touchControl('climb',1)}><MoveUp/></button><button aria-label="下降" {...touchControl('climb',-1)}><MoveDown/></button><button aria-label="悬停" {...touchControl('hover',true)}><Pause/></button></div></>}
   {flight.mode==='passenger'&&<div className="journey-card glass"><div><MapPin size={15}/><strong>中环 <ArrowRight size={12}/> 西九龙</strong><span>{fmt(flight.routeSeconds)} / 05:30</span></div><div className="journey-track"><i style={{width:`${flight.routeSeconds/330*100}%`}}/><b style={{left:`${flight.routeSeconds/330*100}%`}}/></div><small>{flight.visitedLandmarks.length} 个地标已发现</small></div>}
   <div className="camera-dock glass" role="group" aria-label="镜头与摄影">{Object.entries(cameraNames).map(([id,name])=><button key={id} className={flight.camera===id?'active':''} aria-pressed={flight.camera===id} onClick={()=>changeCamera(id)}>{id==='window'?<Eye size={19}/>:id==='forward'?<Navigation size={19}/>:<Plane size={19}/>}<span>{name}</span></button>)}<i/><button onClick={takePhoto}><Camera size={20}/><span>拍照</span></button></div>
   <div className="look-hint">拖动环顾 <span>·</span> <button onClick={()=>apiRef.current?.resetView()}>回正视角</button></div>
   {flight.notice&&<div className="notice glass" role="status">{flight.notice}{flight.control==='holding'&&<button onClick={()=>changeMode('passenger')}>重试接回</button>}</div>}
  </>}
  <aside className="side-tools glass"><IconButton icon={settings.audio?Volume2:VolumeX} label={settings.audio?'关闭声音':'开启声音'} onClick={()=>setSettings({...settings,audio:!settings.audio})}/><IconButton icon={ImageIcon} label="打开相册" onClick={()=>openModal('gallery')}/><IconButton icon={fullscreen?Minimize:Maximize} label={fullscreen?'退出全屏':'全屏'} onClick={toggleScreen}/></aside>
  <footer className="footer"><button onClick={()=>openModal('about')}>未来出行概念体验 <Info size={11}/></button><span>{!storageOk?'本机存档暂不可用':inFlight?'进度自动保存在本机':'真实地理 · 未来想象'}</span></footer>
  {toast&&<div className="toast glass" role="status"><Check size={17}/>{toast}</div>}{flash&&<div className="photo-flash"/>}
  {landmark&&<div className="landmark-detail glass"><button className="close-small" aria-label="关闭地标介绍" onClick={()=>setLandmark(null)}><X size={16}/></button><span className="eyebrow">CITY DISCOVERY</span><h2>{landmark.name}</h2><p>{landmark.description}</p><small><Check size={12}/>已收录到本次航程</small></div>}
  {paused&&!modal&&<div className="pause-overlay"><section className="dialog glass"><span className="eyebrow">TAKE YOUR TIME</span><h2>风景，等你回来。</h2><p>{flight.pauseReason==='focus'?'你离开页面时，航程已自动暂停。':'航程已暂停，当前位置已保存。'}</p><button className="primary" onClick={()=>pause(null)}><Play size={18}/>继续飞行</button><button className="text-button" onClick={goHome}>返回起降场</button></section></div>}
  {arrived&&!modal&&<div className="pause-overlay"><section className="dialog glass arrival"><span className="eyebrow">WELCOME TO WEST KOWLOON</span><div className="arrival-icon"><Check size={26}/></div><h2>你好，西九龙。</h2><p>一段新的城市记忆，已抵达。</p><div className="arrival-stats"><span><strong>{fmt(flight.elapsedSeconds)}</strong>飞行时间</span><span><strong>{flight.visitedLandmarks.length}</strong>发现地标</span><span><strong>{photos.length}</strong>本机照片</span></div><button className="primary" onClick={()=>start(false)}>再飞一次<ArrowUpRight size={18}/></button><button className="text-button" onClick={goHome}>返回起降场</button></section></div>}
  {modal&&<div className="modal-backdrop" onClick={e=>{if(e.target===e.currentTarget)setModal(null);}}><section className={`dialog glass modal-${modal}`} role="dialog" aria-modal="true" aria-labelledby="dialog-title"><IconButton icon={X} label="关闭窗口" onClick={()=>setModal(null)}/>
   {modal==='settings'&&<><span className="eyebrow">MAKE YOURSELF COMFORTABLE</span><h2 id="dialog-title">飞行偏好</h2><Setting label="座舱声音" sub="轻柔的电机与飞行环境音" checked={settings.audio} onChange={v=>setSettings({...settings,audio:v})}/><Setting label="地标提示" sub="在风景中发现香港" checked={settings.labels} onChange={v=>setSettings({...settings,labels:v})}/><Setting label="航线引导" sub="轻驾驶时显示空中参考线" checked={settings.route} onChange={v=>setSettings({...settings,route:v})}/><Setting label="舒缓镜头" sub="减少镜头过渡时间" checked={settings.reducedMotion} onChange={v=>setSettings({...settings,reducedMotion:v})}/><div className="setting-row"><div><strong>画面质量</strong><small>卡顿时可以选择流畅</small></div><select aria-label="画面质量" value={settings.quality} onChange={e=>setSettings({...settings,quality:e.target.value})}><option value="high">清晰</option><option value="low">流畅</option></select></div></>}
   {modal==='gallery'&&<><span className="eyebrow">YOUR HONG KONG, FROM ABOVE</span><h2 id="dialog-title">空中相册 <small>{photos.length} / 12</small></h2><p>照片保存在当前浏览器。下载后，可以随时带走。</p>{photos.length?<div className="photo-grid">{photos.map(p=><article key={p.id}><img src={p.image} alt={`维港${p.camera}视角，航程 ${p.time}`}/><div><span>{p.camera} · {p.time}</span><IconButton icon={Download} label="下载照片" onClick={()=>downloadPhoto(p)}/><IconButton icon={Trash2} label="删除照片" onClick={async()=>{await photoStore('delete',p.id);setPhotos(photos.filter(x=>x.id!==p.id));}}/></div></article>)}</div>:<div className="empty-gallery"><Camera size={38}/><h3>把喜欢的风景留下来</h3><p>飞行中点击“拍照”，照片就会出现在这里。</p></div>}</>}
   {modal==='about'&&<><span className="eyebrow">NEXTGEN EVTOL / PROTOTYPE 01</span><h2 id="dialog-title">真实香港，未来想象。</h2><p>以维多利亚港为舞台的未来出行体验。NG-01、起降场和航线均为游戏概念。</p><dl><dt>城市与山形</dt><dd>OpenStreetMap 建筑轮廓；缺失高度按建筑类型估算。Mapzen 开放 DEM 地形；Esri 在线卫星影像。核心地标为简化模型。</dd><dt>数据范围</dt><dd>香港区域地形、维港周边建筑。首版可驾驶范围为维港观景区。</dd><dt>地理精度</dt><dd>场景高度是近似值。不是香港官方精细三维模型，不用于真实飞行导航。</dd><dt>开源基础</dt><dd>CesiumJS · Resium · React。镜头播放设计参考 Flight3DView。</dd></dl><p className="source-links"><a href="https://www.openstreetmap.org/copyright" target="_blank" rel="noreferrer">© OpenStreetMap contributors</a><a href="https://registry.opendata.aws/terrain-tiles/" target="_blank" rel="noreferrer">Mapzen 地形来源</a></p></>}
   {modal==='menu'&&<><span className="eyebrow">YOUR FLIGHT</span><h2 id="dialog-title">航程菜单</h2><p>中环海滨 → 西九龙海滨</p><button className="primary" onClick={()=>{setModal(null);pause(null);}}><Play size={18}/>继续飞行</button><button className="text-button" onClick={goHome}><House size={15}/>返回起降场</button></>}
  </section></div>}
 </main>;
}
function Setting({label,sub,checked,onChange}){return <label className="setting-row"><span><strong>{label}</strong><small>{sub}</small></span><input type="checkbox" checked={checked} onChange={e=>onChange(e.target.checked)}/><span className="toggle"/></label>;}
function RouteSketch(){return <div className="route-sketch"><svg viewBox="0 0 360 88" aria-label="中环至西九龙概念航线示意"><path d="M0 70L38 63 54 68 83 50 118 56 126 66 149 60 176 80 181 88H0Z" fill="#c2d8db"/><path d="M214 0L219 13 242 18 254 10 276 25 308 18 339 39 360 29V0Z" fill="#c2d8db"/><path d="M61 63C102 13 222 74 303 24" fill="none" stroke="#668e9d" strokeWidth="1.5" strokeDasharray="4 4"/><circle cx="61" cy="63" r="5" fill="#234e60"/><circle cx="61" cy="63" r="2" fill="white"/><circle cx="303" cy="24" r="5" fill="#234e60"/><circle cx="303" cy="24" r="2" fill="white"/><path d="M175 43l13 1-4-7 4-2 6 9 13 5-1 3-13-2-9 6-3-2 6-7-13-2z" fill="#285468"/><text x="28" y="82">中环</text><text x="307" y="14">西九龙</text></svg></div>;}
createRoot(document.getElementById('root')).render(<ErrorBoundary><App/></ErrorBoundary>);
